# Generated by Django 5.1.6 on 2025-03-12 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bid_comment_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='categorie',
            field=models.CharField(choices=[('--', 'Sans Catégorie'), ('MO', 'Mode'), ('JO', 'Jouets'), ('EL', 'Électronique'), ('MA', 'Maison')], max_length=64, null=True),
        ),
    ]
