# Generated by Django 5.1.6 on 2025-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='actif',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
