# Generated by Django 5.1.6 on 2025-03-14 21:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_users_interesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='encheres', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='encherisseur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='encheres', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='valeur_enchere',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
