# Generated by Django 5.1.6 on 2025-03-17 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_article_bid_date_creation_bid_encherisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='gagnant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_gagnes', to=settings.AUTH_USER_MODEL),
        ),
    ]
