# Generated by Django 5.1.6 on 2025-03-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_commentaire_comment_article_comment_auteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Commentaire',
            new_name='commentaire',
        ),
    ]
